blank_issues_enabled: false
contact_links:
  - name: Ra93 Core Discord Server
    url: https://discord.gg/VrrHWnMuft
    about: Ask questions, receive support, and discuss with the community in our Discord server.
